### ISSUE TITLE
Read sites and domains from a config file

### ISSUE THREAD

**Issue by Cephlin** [mypebble/infrastructure-monitor#2]
Should be able to read in a yaml config file with the style:

```

---
sites:
- url: example.com
  status_code: 200
- url: example.co.uk
  status_code: 302
domains:
- url: 8.8.8.8
```
